# development environment for holopy
#
# To use:
#   conda env create -f ./environment.yml
# and then
#   conda activate holopy-devel
#
# To update dependencies after changing this environment file:
#   conda env update --name holopy-devel --file environment.yml --prune
#
# can also use mamba instead of conda in the above
name: holopy-devel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy<1.20
  - scipy
  - pyyaml
  - pillow
  - pandas
  - xarray
  - h5netcdf
  - h5py
  - numexpr
  - matplotlib
  - emcee=2.2.1
  - schwimmbad
  - memory_profiler
  - cma
  - ipython
  - seaborn
  # installs compilers on linux and OSX
  # - compilers
  # for amd64 platforms only; won't be found for aarch64
  # - mkl-service
  # uncomment to install compilers on windows
  #  - m2w64-toolchain

  # for building documentation
  - sphinx
  - sphinx_rtd_theme
  - numpydoc


  # for building fortran extensions and python package
  - meson
  - meson-python

  # for running tests: "cov" is coverage plugin, "xdist" is to run pytest in
  # parallel; "timeout" is to set timeout for tests
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-timeout

  # optional packages to make development easier in (e.g.) emacs
  - pyright
  - pylint
  - flake8
  - flake8-pytest-style
  - autoflake
  - epc
  - isort
  - yapf
  - debugpy
  - pip

  - pip:
      - importmagic

  # include jupyterlab for convenience
  - jupyterlab

